### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by connor-baer** [sumup/circuit-ui#127]
## Publication

- [x] Create a build task for distribution #266
- [ ] Select and add license #321
- [ ] Host static CSS file for easy use

## Documentation

- [x] Finish documentation website ([circuit.sumup.com](https://circuit.sumup.com))
- [x] Add a concrete example of an app using ⚡Circuit UI #126 

## Collaboration 

- [ ] Add contributing guideline #319 #320
- [x] Add GitHub issue and PR templates #318

**Comment by mlent** [comment]
I think there are some components missing, which need input from design:

- [] Fully-fledged CC input (@Inkyov is working on one with validations but we need design/interaction too)
- [] Modals
- [] Selected cards
- [] Table component
- [] Link component

Plus:
- [] Usage guidelines from design in the circuit-docs

These are the main ones that come to mind. Not sure if it matters really for v1 though, as for that I guess we just want a stable API for components we _do_ have?

**Comment by rostero1** [comment]
https://choosealicense.com/no-permission/
